### ISSUE TITLE
Does not seem to have access to files stored on OpenAI

### ISSUE THREAD

**Issue by Leonardo-Fiori** [supercorp-ai/superinterface#4]
I have an existing OpenAI GPT Assistant on my OpenAI API dashboard. I use it through the playground function but it is really terrible because it keeps logging me off, and every time it looses the thread so I need to start a new one. I found Superinterface.ai and thought it would be an amazing way to interface with my existing GPT assistant, so I linked it with my API keys and selected the assistant but the issue seems to be that it does not read the files stored on OpenAI that I use to "instruct" my assistant on information about what it needs to do. Specifically it's a .txt file containing all the data scraped from my blog, looks like when I chat with the assistant on Superinterface.ai, it is not aware of the file.

**Comment by Nedomas** [comment]
Thanks for the info! Superinterface is just the UI infrastructure layer for the OpenAI assistant so it definitely should see the same exact files as the OpenAI assistants see. Will investigate and get back to you.

**Comment by Nedomas** [comment]
It was an OpenAI config problem. Me and @Leonardo-Fiori managed to solve it.
